import React from "react";
import Head from "next/head";
import Link from "next/link";
import { Navbar, Hero, Footer, Card } from "../../components";

const index = () => {
  return (
    <>
      <Head>
        <title>Blog - Santajit Patra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen w-screen flex-col bg-gradient-to-tr  from-blue-500 to-purple-500">
        <Navbar />
        <div className="relative h-screen overflow-hidden bg-gradient-to-br from-cyan-300 to-blue-900">
          {/* <img src="/yt.png" className="absolute object-cover w-full h-full" /> */}
          <div className="absolute inset-0 bg-black opacity-25"></div>
          <div className="container relative z-10 flex items-center px-6 py-32 mx-auto md:px-12 xl:py-40">
            <div className="relative z-10 flex flex-col items-center w-full h-full">
              <h2 className="text-white text-9xl text-center font-black">
                Blog
              </h2>
              <p className="text-xl text-center text-white font-normal m-6">
                No blog available right now.
              </p>

              <Link
                href="/home"
                className="mb-3 inline-flex h-12 w-full items-center justify-center px-6 font-medium tracking-wide shadow-md transition duration-200 focus:outline-none md:mr-4 md:mb-0 md:w-auto text-white hover:text-yellow-50 bg-gradient-to-r  from-pink-500 to-purple-500 hover:from-cyan-600 hover:to-blue-600 rounded-full"
              >
                Back To Homepage
              </Link>
            </div>
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
};

export default index;
