import Head from "next/head";
import { Navbar,Footer,} from "../components";
import Link from "next/link";

const about = () => {
  return (
    <>
      <Head>
        <title>About - Santajit Patra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen w-screen flex-col bg-gradient-to-tr  from-blue-500 to-purple-500">
        <Navbar />
        <>
  <div className="flex min-h-screen w-screen">
    <div className="relative my-auto mx-auto flex flex-col px-4 sm:max-w-xl md:max-w-screen-xl md:flex-row">
      {/* Left Column */}
      <div className="mx-auto flex w-full max-w-xl lg:max-w-screen-xl">
        <div className="mb-16 lg:my-auto lg:max-w-lg">
          <div className="mb-6 max-w-xl">
          <h2 className="mb-6 max-w-lg font-sans text-3xl font-bold leading-snug tracking-tight text-white sm:text-5xl sm:leading-snug">
                Let me tell you
                <span className="my-1 inline-block rounded bg-white px-2 text-violet-600">
                About
                </span>
                <span className="text-cyan-300">Me</span>
              </h2>
              <p className="text-base text-gray-200">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum
                in ipsam, ea incidunt pariatur tempora perferendis esse velit
                aspernatur mollitia illum consectetur tempore asperiores facilis
                ratione voluptates non possimus dolores!
              </p>
          </div>
        </div>
      </div>
      {/* /Left Column */}
      {/* Right Column */}
      <div className="flex h-full w-full space-x-3 overflow-hidden md:justify-end">
        {/* Col 2 */}
        <div className="hidden w-56 items-center space-y-3 lg:flex">
          <div className="overflow-hidden rounded-xl bg-yellow-400">
            <img
              className="h-full w-full object-cover"
              src="https://images.unsplash.com/photo-1544376798-89aa6b82c6cd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80"
              alt=""
            />
          </div>
        </div>
        <div className="w-full flex-col space-y-3 rounded-xl py-4 lg:flex lg:w-80">
          <div className="h-40 overflow-hidden rounded-xl bg-green-600/60">
            <img
              className="mx-auto h-full w-full object-cover"
              src="https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80"
              alt=""
            />
          </div>
          <div className="h-40 overflow-hidden rounded-xl bg-pink-600/60">
            <img
              className="mx-auto h-full w-full object-cover"
              src="https://images.unsplash.com/photo-1511884642898-4c92249e20b6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
              alt=""
            />
          </div>
          <div className="h-40 overflow-hidden rounded-xl bg-blue-600/60">
            <img
              className="mx-auto h-full w-full object-cover"
              src="https://images.unsplash.com/photo-1434725039720-aaad6dd32dfe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1342&q=80"
              alt=""
            />
          </div>
        </div>
      </div>
      {/* /Right Column */}
    </div>
  </div>
</>


        <Footer />
      </div>
    </>
  );
};

export default about;
