import Head from "next/head";
import { AboutDescription, Whatsapp } from "../components";
import { Navbar, Header, Footer } from "../components/layouts";
// import { websiteDev } from "../constants/images";


const about = () => {
  return (
    <>
      <Head>
        <title>About - Santajit Patra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen w-screen flex-col text-white  BG">
        <Navbar />
        <Header title="About" bg='url("https://images.pexels.com/photos/3862132/pexels-photo-3862132.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")' />
        <AboutDescription />
        <Footer />
        <Whatsapp />
      </div>
    </>
  );
};

export default about;
