import Head from "next/head";
import { Map, ContactForm, Whatsapp} from "../components";
import { Navbar, Header, Footer} from "../components/layouts";


const contact = () => {
  return (
    <>
      <Head>
        <title>Contact - Santajit Patra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen w-screen flex-col BG">
        <Navbar />
        <Header
          title="Contact"
          bg='url("https://images.unsplash.com/photo-1611746869696-d09bce200020?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80")'
        />
        <ContactForm />
        <Map />
        <Footer />
        <Whatsapp />
      </div>
    </>
  );
};

export default contact;
