import Head from "next/head";
import { Navbar,Header, Footer,  Map, ContactForm, Whatsapp} from "../components";
// import Link from "next/link";

const contact = () => {
  return (
    <>
      <Head>
        <title>Contact - Santajit Patra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen w-screen flex-col BG">
        <Navbar />
        <Header title="Contact" bg='url("./contactus.jpg")' />
        <ContactForm />
        <Map />
      <Footer />
      <Whatsapp />
      </div>
    </>
  );
};

export default contact;
