import Head from "next/head";
import { Navbar, Hero, Footer, Card, CTA } from "../components";

const Home = () => {
  return (
    <>
      <Head>
        <title>Santajit Patra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen w-screen flex-col bg-gradient-to-tr  from-blue-500 to-purple-500">
        <Navbar />
        <Hero />
        <Card />
        <CTA />
        <span className="h-16"></span>
        <Footer />
      </div>
    </>
  );
};

export default Home;
