import Head from "next/head";
import { Navbar, Hero, Footer, Card, CTA, ContactForm, ServicesOffer, Whatsapp} from "../components";

const Home = () => {
  return (
    <>
      <Head>
        <title>Santajit Patra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen w-screen flex-col bg-gradient-to-tr  from-blue-500 to-purple-500">
        <Navbar />
        <Hero />
        <Card />
        <CTA />
        <h2 className="mt-12 text-center font-sans text-5xl font-bold text-white">
          Our Services
        </h2>
        <ServicesOffer />
        <h2 className="text-center font-sans text-5xl font-bold text-white">
          Contact Us
        </h2>
        <ContactForm />
        <Footer />
        <Whatsapp />
      </div>
    </>
  );
};

export default Home;
