import Home from "../components/home";
import Head from "next/head";

const index = () => {

  return (
    <div>
      <Head>
        <title>Santajit Patra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
    </div>
  );
};

export default index;
