import React from "react";
import Head from "next/head";
import {
  PortfolioRight,
  PortfolioLeft,
  Whatsapp,
  PortfolioCTA,
} from "../components";
import { Navbar, Header, Footer } from "../components/layouts";
import {
  project1,
  project2,
  project3,
  project4,
  project5,
  project6,
  project7,
  project8,
  project9,
  project10,
} from "@/constants/images";
import workDB from "../constants/workdb";
import Project from "../components/Project";



const portfolio = () => {
  return (
    <div>
      <Head>
        <title>Portfolio - Santajit Patra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen w-screen flex-col BG">
        <Navbar />
        <Header
          title="Portfolio"
          bg='url("https://images.pexels.com/photos/943096/pexels-photo-943096.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")'
        />

        <div className="container my-24 px-6 mx-auto">
          <div className="flex flex-col ">
            {workDB.map(
              ({
                title,
                description,
                name,
                about,
                image,
                button,
                buttonSource,
              }) => (
                <Project
                  key={title}
                  title={title}
                  description={description}
                  name={name}
                  about={about}
                  image={image}
                  button={button}
                  buttonSource={buttonSource}
                />
              )
            )}
          </div>
        </div>
        <PortfolioCTA />
        <Footer />
        <Whatsapp />
      </div>
    </div>
  );
};

export default portfolio;
