import Head from "next/head";
import Image from "next/image";
import { Navbar, Footer } from "../components";

const services = () => {
  return (
    <>
      <Head>
        <title>Seervices - Santajit Patra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex min-h-screen w-screen flex-col text-white bg-gradient-to-tr  from-blue-500 to-purple-500">
        <Navbar />

        <div className="mx-auto mt-20 flex w-full flex-col items-center justify-center sm:max-w-screen-sm md:max-w-screen-md lg:flex-row">
          <div className="text-center">
            <h2 className="bg-clip-text text-5xl font-extrabold sm:text-5xl">
              Services
            </h2>
          </div>
        </div>

        {/* <!-- ======================================== 
                   service Section Start/End 
            ========================================  --> */}

        <section className="">
          <div className="mx-auto grid max-w-lg gap-x-8 gap-y-12 px-4 py-32 md:max-w-screen-xl md:grid-cols-2 md:px-8 lg:grid-cols-3">
            <div className="p-12">
              <h2 className="text-3xl font-medium text-white">
                WE HELP YOU <br />
                ACHIEVE YOUR GOALS
              </h2>
            </div>
            <div className="relative w-72 xl:w-96 h-56 p-4 overflow-hidden bg-white shadow-lg rounded-2xl px-4 pt-14 pb-8">
              <Image
                alt="moto"
                src="/santajit-patra-11.jpeg"
                className="absolute w-40 h-40 mb-4 rounded-full -right-20 -bottom-8"
                width={500}
                height={500}
              />
              <div className="w-4/6">
                <p className="mb-2 text-xl font-medium text-gray-800">
                  Web Designing & Development
                </p>
                <p className="text-sm text-gray-400">
                  Leverage the web for your business advantage
                </p>
              </div>
            </div>
            <div className="relative w-72 xl:w-96 h-56 p-4 overflow-hidden bg-white shadow-lg rounded-2xl px-4 pt-14 pb-8">
              <Image
                alt="moto"
                src="/santajit-patra-11.jpeg"
                className="absolute w-40 h-40 mb-4 rounded-full -right-20 -bottom-8"
                width={500}
                height={500}
              />
              <div className="w-4/6">
                <p className="mb-2 text-xl font-medium text-gray-800">
                  Digital Marketing Services
                </p>
                <p className="text-sm text-gray-400">
                  Bolster your presence in digital space
                </p>
              </div>
            </div>
            <div className="relative w-72 xl:w-96 h-56 p-4 overflow-hidden bg-white shadow-lg rounded-2xl px-4 pt-14 pb-8">
              <Image
                alt="moto"
                src="/santajit-patra-11.jpeg"
                className="absolute w-40 h-40 mb-4 rounded-full -right-20 -bottom-8"
                width={500}
                height={500}
              />
              <div className="w-4/6">
                <p className="mb-2 text-xl font-medium text-gray-800">
                  Graphic Design
                </p>
                <p className="text-sm text-gray-400">
                  Bolster your presence in digital space
                </p>
              </div>
            </div>
            <div className="relative w-72 xl:w-96 h-56 p-4 overflow-hidden bg-white shadow-lg rounded-2xl px-4 pt-14 pb-8">
              <Image
                alt="moto"
                src="/santajit-patra-11.jpeg"
                className="absolute w-40 h-40 mb-4 rounded-full -right-20 -bottom-8"
                width={500}
                height={500}
              />
              <div className="w-4/6">
                <p className="mb-2 text-xl font-medium text-gray-800">
                  Virtual Assistant
                </p>
                <p className="text-sm text-gray-400">
                  Bolster your presence in digital space
                </p>
              </div>
            </div>
            <div className="relative w-72 xl:w-96 h-56 p-4 overflow-hidden bg-white shadow-lg rounded-2xl px-4 pt-14 pb-8">
              <Image
                alt="moto"
                src="/santajit-patra-11.jpeg"
                className="absolute w-40 h-40 mb-4 rounded-full -right-20 -bottom-8"
                width={500}
                height={500}
              />
              <div className="w-4/6">
                <p className="mb-2 text-xl font-medium text-gray-800">
                  Digital Marketing Services
                </p>
                <p className="text-sm text-gray-400">
                  Bolster your presence in digital space
                </p>
              </div>
            </div>
          </div>
        </section>
        {/* <!-- ====================   ====================  -->  */}

        <div className="relative mx-auto w-full pb-32 pt-8 text-black">
          <div className="absolute inset-0 bottom-56 bg-slate-100" />
          <div className="relative pt-20 mx-auto w-full max-w-screen-xl px-2 text-left sm:px-10">
            <div className="rounded-xl bg-white shadow-lg shadow-blue-200 lg:flex">
              <div className="flex flex-col p-4 pb-6 sm:p-10 sm:pt-14 lg:w-2/5">
                <div className="flex-auto">
                  <h2 className="text-2xl font-black">
                    Keep Track of Your Projects from Start to Finish
                  </h2>
                  <p className="pt-4">
                    Create tasks, track time, share with colleagues, nd share
                    progress in real time.
                  </p>
                  <div className="mt-6 flex flex-wrap">
                    <p className="m-1 rounded-md text-gray-600 bg-gray-100 px-2 py-1 text-sm">
                      Web development
                    </p>
                    <p className="m-1 rounded-md text-gray-600 bg-gray-100 px-2 py-1 text-sm">
                      Graphic design
                    </p>
                    <p className="m-1 rounded-md text-gray-600 bg-gray-100 px-2 py-1 text-sm">
                      Social media marketing
                    </p>
                    <p className="m-1 rounded-md text-gray-600 bg-gray-100 px-2 py-1 text-sm">
                      Virtual assistance
                    </p>
                  </div>
                </div>
              </div>
              <div className="m-8 lg:w-3/5 hidden overflow-hidden rounded-xl sm:block">
                <Image
                  src="/seox.png"
                  alt="Picture of the author"
                  width={500}
                  height={500}
                />
              </div>
            </div>
          </div>
        </div>
        {/* <!-- ======================================== 
                          automation Section Start/End 
                  ========================================  -->  */}
        <section className="text-white y-10 leading-6 sm:py-16 lg:py-24">
          <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
            <div className="mx-auto text-center">
              <h2 className="mb-3 pb-2 text-4xl font-semibold md:text-7xl">
                <span className="font-light">Have a look </span>Around!
              </h2>
              <p className="mb-3 font-light">
                And you will find everything you need to build a great business.
              </p>
            </div>
            <div className="mt-8 grid grid-cols-1 gap-6 sm:grid-cols-2 md:gap-8 lg:mt-16 lg:grid-cols-4">
              <div className="relative overflow-hidden border-t-4 border-blue-500 bg-gray-600 shadow">
                <div className="px-6 py-10">
                  <div className="flex items-center">
                    <h3 className="relative ml-2 inline-block text-4xl font-bold leading-none">
                      75%
                    </h3>
                    <span className="ml-3 text-base font-medium capitalize">
                      Data Entry & Management{" "}
                    </span>
                  </div>
                </div>
              </div>
              <div className="relative overflow-hidden border-t-4 border-blue-500 bg-gray-600 shadow">
                <div className="px-6 py-10">
                  <div className="flex items-center">
                    <h3 className="relative ml-2 inline-block text-4xl font-bold leading-none">
                      47%
                    </h3>
                    <span className="ml-3 text-base font-medium capitalize">
                      Research & Market Analysis{" "}
                    </span>
                  </div>
                </div>
              </div>
              <div className="relative overflow-hidden border-t-4 border-blue-500 bg-gray-600 shadow">
                <div className="px-6 py-10">
                  <div className="flex items-center">
                    <h3 className="relative ml-2 inline-block text-4xl font-bold leading-none">
                      66%
                    </h3>
                    <span className="ml-3 text-base font-medium capitalize">
                      Customer Service & Lead Generation{" "}
                    </span>
                  </div>
                </div>
              </div>
              <div className="relative overflow-hidden border-t-4 border-blue-500 bg-gray-600 shadow">
                <div className="px-6 py-10">
                  <div className="flex items-center">
                    <h3 className="relative ml-2 inline-block text-4xl font-bold leading-none">
                      34%
                    </h3>
                    <span className="ml-3 text-base font-medium capitalize">
                      Marketing & Search Engine Optimization{" "}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <Footer />
      </section>
    </>
  );
};

export default services;
