import Head from "next/head";
import { Navbar, Header, Footer, ServicesOffer, Performance, Whatsapp, ServicesCTA } from "../components";

const services = () => {
  return (
    <>
      {/* <!-- ==================== head  ====================  -->  */}

      <Head>
        <title>Seervices - Santajit Patra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <!-- ==================== Head  ====================  -->  */}

      <section className="flex min-h-screen w-screen flex-col BG">
        <Navbar />
        <Header title="Services" bg='url("./services.jpg")'/>
        <ServicesOffer />
        <ServicesCTA />
        <Performance />
        <Footer />
        <Whatsapp />
      </section>
    </>
  );
};

export default services;
